#!/usr/bin/bash

#start swwww
swww query || swww init

#figure out which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#show the correct wallpapper based on the theme
if [ $THEMEIS == "dark.css" ]; then
    swww img ~/.config/hypr/wallpaper-dark.jpg
	gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Standard-Mauve-Dark"
	gsettings set org.gnome.desktop.interface icon-theme 'Tela-purple-dark'
	gsettings set  org.gnome.desktop.interface cursor-theme 'Catppuccin-Mocha-Dark'
else
    swww img ~/.config/hypr/latte.jpg
	gsettings set org.gnome.desktop.interface icon-theme 'Tela-green'
	gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Latte-Standard-Green-Light"
	gsettings set  org.gnome.desktop.interface cursor-theme 'Catppuccin-Latte-Light'
fi
